### ISSUE TITLE
friend，can you help me？

### ISSUE THREAD

**Issue by Chenjiek** [marcolinuxbr/attiny12#1]
Hello, my friend, I have tried many methods, but I cannot upload the hex file to the ATtiny12, meaning I cannot burn the program. Can you help me? Which software and hardware should I use?

**Comment by marcolinuxbr** [comment]
I dont program microcontrollers in a long time, lol, dont remember.
I dont use windows , just use  linux.

But you can use avrdude (software) and usb/serial (USBasp / hardware)

Try this link:
https://skjoldtech.wordpress.com/2019/05/10/flashing-arduino-hex-file-in-linux-with-avrdude/

**Comment by Chenjiek** [comment]
I am very happy to get your reply. Now it seems that I think the problem lies in the microcontroller I bought. Although the problem is still not solved, thank you for taking the time to answer me. I am from China, thank you!
